### ISSUE TITLE
Add test on each parser in toPath function

### ISSUE THREAD

**Issue by frinyvonnick** [zenika-open-source/immutadot#146]
### Prerequisites
 - [x] I have read the [Contributing guidelines](https://github.com/Zenika/immutadot/blob/master/.github/CONTRIBUTING.md)
 - [x] I have read the [Code of conduct](https://github.com/Zenika/immutadot/blob/master/.github/CODE_OF_CONDUCT.md) and I agree with it

### Description
I suggest to test each parser made in #115 to make further improvements easier to do.

**Comment by nlepage** [comment]
Tests will have a way better granularity, this should avoid code comments that are not reflected in the `it('...')` like this :
```js
    // Unterminated list notation should give a prop
    expect(toPath('abc.{')).toEqual([[prop, 'abc'], [prop, '{']])
```

**Comment by nlepage** [comment]
We must still have general tests.
This would be a good fit for random testing, it's very easy to generate a path and the resulting parsed path.

**Comment by frinyvonnick** [comment]
This function have been moved and totally rewritten
