### ISSUE TITLE
apply: Improve already applied paths

### ISSUE THREAD

**Issue by nlepage** [zenika-open-source/immutadot#153]
### Description
In `apply`, for now "already applied paths" are theoric.
For paths containing slices this means that we don't really know if copies were made, which indexes of slices were copied, the entire structure might not have been copied...
That's why path containing slices are filtered from already applied paths...

Improve `apply` in order to know really applied paths and avoid unnecessary copies...

**Comment by frinyvonnick** [comment]
Already applied paths doesn't exist anymore in 2.0.0
