### ISSUE TITLE
Update runkit example of immutadot-lodash

### ISSUE THREAD

**Issue by frinyvonnick** [zenika-open-source/immutadot#335]
### Prerequisites
 - [x] I have read the [Contributing guidelines](https://github.com/Zenika/immutadot/blob/master/.github/CONTRIBUTING.md)
 - [x] I have read the [Code of conduct](https://github.com/Zenika/immutadot/blob/master/.github/CODE_OF_CONDUCT.md) and I agree with it

### Description
It misses the orderBy import

**Comment by nlepage** [comment]
Duplicate of #226
